### ISSUE TITLE
01 sample is using the implicit flow instead of code flow. 

### ISSUE THREAD

**Issue by rsmcode** [auth0-samples/auth0-express-webapp-sample#10]
I presume for this sample, it is better to demonstrate the code flow.  01-sample uses the implicit flow which isn't ideal for regular apps.

https://github.com/auth0/express-openid-connect/blob/master/API.md#authorization-params-key

**Comment by adamjmcgrath** [comment]
Sorry for not replying to this sooner @rsmcode - the Implicit flow (with form post) is still our recommended flow for web apps that only want to do sign in (don't want an access token). See https://auth0.com/docs/get-started/authentication-and-authorization-flow/implicit-flow-with-form-post
