### ISSUE TITLE
Setup new laptop Window 10 Getting those issue with auth 0

### ISSUE THREAD

**Issue by gauravverma029** [auth0-samples/auth0-express-webapp-sample#40]
<img width="599" alt="Screenshot 2022-06-12 174657" src="https://user-images.githubusercontent.com/4488516/173241717-e1d51338-6c36-4a2e-aa9c-0814f81f6d28.png">
This application not working with localhost. Any solution here please

**Comment by adamjmcgrath** [comment]
This was answered here https://github.com/auth0/express-openid-connect/issues/360#issuecomment-1153881980
