### ISSUE TITLE
Logging in gives an error: access_denied (Error: getaddrinfo ENOTFOUND undefined)

### ISSUE THREAD

**Issue by omijuankenobi** [auth0-samples/auth0-express-webapp-sample#46]
When I start this sample app and login, I get this error: "access_denied (Error: getaddrinfo ENOTFOUND undefined)". This is visible in the browser as well as in the logs from the Quickstart page on my dashboard (pasted below).

I've specified the "Allowed Callback URLs" and the "Allowed Logout URLs" as described in the instructions. I also tried running a https reverse proxy. 

What am I missing here?

```
{
  "date": "2022-09-23T00:03:10.344Z",
  "type": "f",
  "description": "Error: getaddrinfo ENOTFOUND undefined",
  "connection_id": "",
  "client_id": "xx",
  "client_name": "xx",
  "ip": "x.x.x.x",
  "user_agent": "Chrome 105.0.0 / Mac OS X 10.15.7",
  "details": {
    "body": {},
    "qs": {
      "client_id": "xx",
      "scope": "openid profile email",
      "response_type": "id_token",
      "redirect_uri": "http://localhost:3000/callback",
      "response_mode": "form_post",
      "nonce": "u3aMUzGNXhcP5XAfo1XvNNmAsMAUNrI1PQqqKkbTizI",
      "state": "eyJyZXR1cm5UbyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9"
    },
    "error": {
      "message": "Error: getaddrinfo ENOTFOUND undefined",
      "oauthError": "access_denied",
      "type": "oauth-authorization"
    },
    "session_id": "LNghNMbuuphTy9I9HLqq0N6bX8LSjvK3",
    "stats": {
      "loginsCount": 13
    }
  },
  "hostname": "xxx.us.auth0.com",
  "user_id": "auth0|xxx",
  "user_name": "xxx@xxx.xxx",
  "audience": "https://xxx.us.auth0.com/userinfo",
  "scope": [
    "openid",
    "profile",
    "email"
  ],
  "log_id": "90020220923000314746157585488925899669990466254387806258",
  "_id": "90020220923000314746157585488925899669990466254387806258",
  "isMobile": false,
  "id": "90020220923000314746157585488925899669990466254387806258"
}
```

**Comment by adamjmcgrath** [comment]
Hi @omijuankenobi - thanks for raising this

Do you have a custom rule setup? Also, if you can share your tenant domain, I might be able to investigate.

**Comment by omijuankenobi** [comment]
I do not have any custom rules setup. My tenant domain is
climatize.us.auth0.com.

Thanks for the help, Adam!

**Comment by adamjmcgrath** [comment]
Hi @omijuankenobi - You have a custom rule setup called "Registration webhook" which makes a request to a url dynamically crafted from your client metadata. But your client has no metadata associated with it, so the request url is invalid and the request is failing with `getaddrinfo ENOTFOUND undefined`

**Comment by omijuankenobi** [comment]
Oops, I didn't notice that. Sorry to have wasted your time. Thanks again.
