### ISSUE TITLE
Passwordless use

### ISSUE THREAD

**Issue by markNZed** [auth0-samples/auth0-express-webapp-sample#60]
Hi, the passwordless feature is described at https://auth0.com/docs/authenticate/passwordless/passwordless-with-new-universal-login could you allow this demo to support that?

**Comment by adamjmcgrath** [comment]
Hi @markNZed - it's out of scope to add passwordless to this basic example, but I've put a branch here for how you would do it https://github.com/auth0-samples/auth0-express-webapp-sample/compare/master...adamjmcgrath-patch-1

(Essentially you add `authorizationParams: { connection: 'email' },` to your config to satisfy https://auth0.com/docs/authenticate/passwordless/passwordless-with-new-universal-login#update-your-application)

**Comment by markNZed** [comment]
Thanks very much @adamjmcgrath but somehow it was working without making that change and after making the change I see  an error `400: nonce mismatch, expected im90K3FaV9BAcZ0l4F6c8WcpHWyrFjqnanyljklf1-Q, got: lGRhDzKxAbnLj8-e_SdN9FciIwJrBsySzEQ2EqR-gNY` Also I am not receiving passcodes to the email I used to create the auth0 admin account - is that normal? (I have checkd spam and tried a few times, including resending)

**Comment by markNZed** [comment]
I take it back about it not working. I reloaded the browser cache and it started working. I guess the server restart on making that change got things out of sync.
